set nocompatible               " be iMproved
filetype off                   " required!

" change mapleader from \ to ,
let mapleader=","

if !isdirectory(expand(expand("~/.vim/bundle/vundle/.git")))
    !git clone https://github.com/gmarik/vundle ~/.vim/bundle/vundle
endif

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle required!
Bundle 'gmarik/vundle'

" File buffer/search plugin
"Bundle 'Command-T'

" Adds menu options for plugins
Bundle 'mbadran/headlights'

" auto close quotes, parenthesis, etc.
Bundle 'Raimondi/delimitMate'

" modify comments easily
Bundle 'scrooloose/nerdcommenter'

" git integration
Bundle 'tpope/vim-fugitive'

" Edit surrounding quotes, parenthesis
Bundle 'tpope/vim-surround'

" Colors
Bundle 'croaker/mustang-vim'
Bundle 'tomasr/molokai'
Bundle 'nanotech/jellybeans.vim'

" Add syntax highlighting for vim
Bundle 'applescript.vim'

" Rope integration for python refactoring
Bundle 'sontek/rope-vim'

"" Vim autocomplete
"Bundle 'Shougo/neocomplcache'
"" Use neocomplcache.
"let g:neocomplcache_enable_at_startup = 1
"let g:neocomplcache_enable_auto_select = 1
"let g:neocomplcache_snippets_dir='~/.vim/bundle/snipmate-snippets/snippets'
"" Recommended key-mappings. 
"" <C-h>, <BS>: close popup and delete backword char. 
"inoremap <expr><BS> neocomplcache#smart_close_popup()."\<C-h>" 


" Revision history for file in vim
Bundle 'sjl/gundo.vim.git'
nnoremap <F5> :GundoToggle<CR>
nnoremap <leader>g :GundoToggle<CR>

" Code analysis (lint, etc.)
Bundle 'scrooloose/syntastic'

" add vim support for puppet
Bundle 'rodjek/vim-puppet'

" File/buffer search plugin, replaces Command-T
Bundle 'kien/ctrlp.vim'
nmap <silent> <leader>t :CtrlP<CR>
nmap <silent> <leader>b :CtrlPBuffer<CR>

" fancy statusline
"Bundle 'Lokaltog/vim-powerline'
"let g:Powerline_symbols="unicode"
Bundle 'Lokaltog/powerline'
set rtp+=~/.vim/bundle/powerline/powerline/bindings/vim

Bundle 'ervandew/supertab'
let g:SuperTabDefaultCompletionType = "context"

Bundle 'skammer/vim-css-color'

Bundle 'majutsushi/tagbar'
if has('mac')
    let g:tagbar_ctags_bin='/usr/local/Cellar/ctags/5.8/bin/ctags'
elseif has('unix')
    let g:tagbar_ctags_bin='/usr/bin/ctags'
endif
" Have F8 toggle the tagbar
nmap <F8> :TagbarToggle<CR>

Bundle 'nathanaelkane/vim-indent-guides'
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_guide_size = 1
" Have F9 toggle the indent guide.
nmap <F9> :IndentGuidesToggle<CR>

"SnipMate
"Install dependencies:
"Bundle "MarcWeber/vim-addon-mw-utils"
"Bundle "tomtom/tlib_vim"
"Bundle "honza/snipmate-snippets"
"Install
"Bundle "garbas/vim-snipmate"

"UltiSnips
Bundle "SirVer/ultisnips"
Bundle "aalvarado/ultisnips-snippets"
let g:UltiSnipsSnippetsDir='~/.vim/bundle/ultisnips-snippets'

"Gist.vim, allows editing of github gists easily
Bundle "mattn/gist-vim"

"vim-endwise, add end's where needed in Ruby
Bundle "tpope/vim-endwise"


filetype plugin indent on     " required!
"
" Brief help
" :BundleList          - list configured bundles
" :BundleInstall(!)    - install(update) bundles
" :BundleSearch(!) foo - search(or refresh cache first) for foo
" :BundleClean(!)      - confirm(or auto-approve) removal of unused bundles
"
" see :h vundle for more details or wiki for FAQ
" NOTE: comments after Bundle command are not allowed.

" Quickly edit/reload the vimrc file
" ev to edit, sv to source
nmap <silent> <leader>ev :e $MYVIMRC<CR>
nmap <silent> <leader>sv :so $MYVIMRC<CR>

set modelines=0     "prevent security exploits
set hidden          "open a new file with :e and just hide the old buffer
set nowrap          "don't wrap lines
set tabstop=4       "a tab is four spaces
set shiftwidth=4    "number of spaces to use for autoindenting
set softtabstop=4
set expandtab       "expand tabs to spaces
set backspace=indent,eol,start "allow backspacking over everything in insert mode
set autoindent      "always set autoindent
set copyindent      "copy the previous indentation on autoindenting
set shiftround      "multiple of shiftwidth when indenting with '<' and '>'
set showmatch       "show matching parenthesis
set ignorecase      "ignore case when searching
set smartcase       "ignore case if search pattern is all lowercase,
                    "case sensitive otherwise
set smarttab        "insert tabs on the start of a line according to
                    "shiftwidth not tabstop
set hlsearch        "highlight search terms
set incsearch       "show search matches as you type
set guioptions-=T   " No toolbar
set encoding=utf-8
set scrolloff=3     " start scrolling before cursor hits end
set showmode
set showcmd
set cursorline
set ttyfast
set ruler "Show information on vim bottom
set laststatus=2
set undofile
set fillchars=vert:\│    " that's a vertical box-drawing character

set history=1000    "remember more commands and search history
set undolevels=1000 "use many levels of undo
set title           " change terminal's title
set visualbell      " don't beep
set noerrorbells    " don't beep
set noshowmode      " Hide teh default mode text (e.g. --INSERT -- )

set completeopt=menuone,longest,preview

set wildmenu                                    " Better file name completion
set wildmode=list:longest,full
set wildignore=*.bak,*.class
set wildignore+=.hg,.git,.svn                    " Version control
set wildignore+=*.aux,*.out,*.toc                " LaTeX intermediate files
set wildignore+=*.jpg,*.bmp,*.gif,*.png,*.jpeg   " binary images
set wildignore+=*.o,*.obj,*.exe,*.dll,*.manifest " compiled object files
set wildignore+=*.spl                            " compiled spelling word lists
set wildignore+=*.sw?                            " Vim swap files
set wildignore+=*.DS_Store                       " OSX bullshit
set wildignore+=migrations                       " Django migrations
set wildignore+=*.pyc                            " Python byte code
set wildignore+=*.orig                           " Merge resolution files

set list
set listchars=tab:>·,trail:·,extends:#,nbsp:·   "Let me see spaces and tabs
                                                "If want eol append ',eol:¬'
set mouse=a                                     "Allow mouse features
set pastetoggle=<F2>                            "No autoindent in paste mode
set gdefault                                    "Defaults to /g for switch

set foldmethod=indent
set foldlevel=99

"always show line numbers, but only in current window
set number
:au WinEnter * :setlocal number
:au WinLeave * :setlocal nonumber

" Automatically resize vertical splits.
:au WinEnter * :set winfixheight
:au WinEnter * :wincmd =

syntax on " switch syntax highlight on

if &t_Co >= 256 || has("gui_running")
  "colorscheme Mustang
  "colorscheme molokai
  colorscheme jellybeans
endif

nnoremap ; :

map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

"nnoremap <leader><space> :noh<cr>
nnoremap <leader><space> :noh<ESC>

" change current file to be opened as 'sudo' and write the file
cmap w!! %!sudo tee > /dev/null %

" Use sane regex
nnoremap / /\v
vnoremap / /\v

nnoremap <tab> %
vnoremap <tab> %

set textwidth=79
set formatoptions=qrn1
set colorcolumn=80

inoremap <up> <nop>
inoremap <down> <nop>
"inoremap <left> <nop>
"inoremap <right> <nop>
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>

" move a line of text using ALT+[jk], indent with ALT+[hl]
nnoremap <A-k> :m-2<CR>==
nnoremap <A-j> :m+<CR>==
nnoremap <A-h> <<
nnoremap <A-l> >>
inoremap <A-j> <Esc>:m+<CR>==gi
inoremap <A-k> <Esc>:m-2<CR>==gi
inoremap <A-h> <Esc><<`]a
inoremap <A-l> <Esc>>>`]a
vnoremap <A-j> :m'>+<CR>gv=gv
vnoremap <A-k> :m-2<CR>gv=gv
vnoremap <A-h> <gv
vnoremap <A-l> >gv

nnoremap <leader>m :silent !open -a Marked.app '%:p'<cr>

au FocusLost * :wa " save when vim loses focus

au VimResized * :wincmd = "resize splits when window resized

inoremap jj <ESC>

noremap <leader>w <C-w>v<C-w>l

if has('gui_running')
    if has('mac')
        set guifont=Inconsolata\ for\ Powerline:h13
    elseif has('unix')
        set guifont=Inconsolata\ for\ Powerline\ 13
    endif
endif

" Specific settings for file types
autocmd FileType ruby set tabstop=2|set shiftwidth=2|set softtabstop=2
autocmd FileType php setlocal noexpandtab|set listchars=tab:>-,trail:·
au BufRead,BufNewFile Vagrantfile set filetype=ruby

function! MakeExecutable()
  silent !chmod a+x %
endfunction

" on save, make file executable if has shebang line with '/bin/'
au BufWritePost * if getline(1) =~ "^#!/bin/" | :call MakeExecutable() | endif

" reselect line after indent
vnoremap < <gv
vnoremap > >gv

" Add the virtualenv's site-packages to vim path
py << EOF
import os.path
import sys
import vim
if 'VIRTUAL_ENV' in os.environ:
    project_base_dir = os.environ['VIRTUAL_ENV']
    sys.path.insert(0, project_base_dir)
    activate_this = os.path.join(project_base_dir, 'bin/activate_this.py')
    execfile(activate_this, dict(__file__=activate_this))
EOF
