# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

gui:
  nerdFontsVersion: "3"
